language: go
go:
  - 1.7
  - tip

install:
  - wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip
  - unzip protoc-3.1.0-linux-x86_64.zip
  - sudo cp bin/protoc /usr/bin/protoc
  - sudo chmod 777 /usr/bin/protoc

before_script:
  - go get github.com/ChimeraCoder/gojson/gojson
  - go generate
  - gofmt -w .
  - test -n $(git status --porcelain)


script:
  go test -v ./...
